DROP TABLE IF EXISTS academic.csv_pending_transfer CASCADE;
DROP TABLE IF EXISTS academic.apprentice_chip CASCADE;
DROP TABLE IF EXISTS academic.instructor_chip CASCADE;
DROP TABLE IF EXISTS academic.instructor_program CASCADE;
DROP TABLE IF EXISTS academic.change_history CASCADE;
DROP TABLE IF EXISTS academic.apprentice CASCADE;
DROP TABLE IF EXISTS academic.chip CASCADE;
DROP TABLE IF EXISTS academic.instructor CASCADE;
DROP TABLE IF EXISTS academic.program CASCADE;