CREATE SCHEMA IF NOT EXISTS security;
CREATE SCHEMA IF NOT EXISTS roleandpermission;
CREATE SCHEMA IF NOT EXISTS academic;
CREATE SCHEMA IF NOT EXISTS environment;
CREATE SCHEMA IF NOT EXISTS facialrecognition;
CREATE SCHEMA IF NOT EXISTS notification;
CREATE SCHEMA IF NOT EXISTS legal;
